{{- range $name, $cfg := .Values.agents }}
{{- if ne (include "openab.agentEnabled" $cfg) "false" }}
{{- if $cfg.discord.botToken }}
{{- $d := dict "ctx" $ "agent" $name "cfg" $cfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openab.agentFullname" $d }}
  labels:
    {{- include "openab.labels" $d | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  discord-bot-token: {{ $cfg.discord.botToken | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
